[tool.poetry]
name = "homework-19-1"
version = "0.1.0"
description = ""
authors = ["Paul Bityakov <p.bitiakov.official@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
